# Generated by Django 4.0.4 on 2022-05-04 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutricional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('valor', models.FloatField()),
                ('detalhes', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pratos/')),
                ('nutricional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutricional.nutricional')),
            ],
        ),
    ]
